# Generated by Django 5.0.4 on 2024-04-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0004_alter_veiculo_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='nome',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
